backend:
  name: git-gateway
  branch: main
locale: cs
media_folder: content/media
public_folder: /media
site_domain: 'https://deti.ochrance.cz/'
display_url: 'https://deti.ochrance.cz/'
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: pages
    label: Stránky
    editor:
      preview: false
    files:
      - label: Homepage
        name: home
        file: content/_index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - label: Youtube na homepage
            name: videos
            required: false
            label_singular: video
            widget: list
            fields:
              - label: Odkaz (youtu.be)
                name: video
                required: false
                widget: string
          - widget: object
            label: PDF s jazykovými variantami
            name: langs
            required: false
            fields:
              - label: PDF v angličtině
                name: en
                required: false
                widget: string
              - label: PDF v němčině
                name: de
                required: false
                widget: string
              - label: PDF v romštině
                name: rom
                required: false
                widget: string
              - label: PDF v ruštině
                name: ru
                required: false
                widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Úvodní text
            name: body
            required: false
            widget: markdown
      - label: Upozornění
        name: varovani
        file: content/alert/_index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - label: Skrýt upozornění
            name: draft
            required: false
            widget: boolean
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Podrobný popis
            name: body
            required: false
            hint: >-
              Titulek se zobrazí na titulní straně, detailní popis na samostatné
              stránce.
            widget: markdown
          - label: Přílohy
            name: attachments
            required: false
            label_singular: Příloha
            widget: list
            fields:
              - label: Název přílohy
                name: title
                widget: string
              - label: Soubor
                name: file
                required: false
                widget: file
              - label: Odkaz
                name: link
                required: false
                widget: string
        media_folder: ''
      - label: Nevíš si rady?
        name: pomoc
        file: content/pomoc/_index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Perex
            name: perex
            required: false
            widget: markdown
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Text
            name: body
            required: false
            widget: markdown
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Linky důvěry
            name: linky
            required: false
            widget: markdown
      - label: Jsem v zařízení…
        name: jsem
        file: content/jsem/_index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Perex
            name: perex
            required: false
            widget: markdown
  - name: aktualne
    label: Aktuálně
    label_singular: aktualita
    folder: content/aktualne
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - label: Uložit jako draft
        name: draft
        required: false
        widget: boolean
      - label: Datum publikování
        name: date
        required: false
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: false
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Perex
        name: perex
        required: false
        widget: markdown
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Text
        name: body
        required: false
        widget: markdown
      - label: Přílohy
        name: attachments
        required: false
        label_singular: Příloha
        widget: list
        fields:
          - label: Název přílohy
            name: title
            widget: string
          - label: Soubor
            name: file
            required: false
            widget: file
          - label: Odkaz
            name: link
            required: false
            widget: string
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    sortable_fields:
      - date
      - commit_date
    summary: '{{day}}. {{month}}. {{year}}: {{title}}'
  - name: kdo-custom
    label: Speciální „Kdo je…“
    editor:
      preview: false
    files:
      - label: O ombudsmanovi
        name: kdo
        file: content/kdo/_index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Perex
            name: perex
            required: false
            widget: markdown
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Fakta
            name: facts
            required: false
            widget: markdown
      - label: Profil ombudsmana
        name: ombudsman
        file: content/kdo/ombudsman/index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - label: Název role
            name: role
            required: false
            widget: string
          - label: Portrét
            name: pic
            required: false
            widget: image
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Text
            name: body
            required: false
            widget: markdown
        media_folder: ''
      - label: Profil zástupce
        name: zastupce
        file: content/kdo/zastupce/index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - label: Název role
            name: role
            required: false
            widget: string
          - label: Portrét
            name: pic
            required: false
            widget: image
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Text
            name: body
            required: false
            widget: markdown
        media_folder: ''
      - label: Jak kontaktovat
        name: kontakt
        file: content/kdo/jak/index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Perex
            name: perex
            required: false
            widget: markdown
          - label: Možnosti kontaktu
            name: contact
            required: false
            label_singular: položka
            widget: list
            fields:
              - label: Název
                name: title
                widget: string
              - &ref_0
                label: Ikona
                name: icon
                required: false
                widget: select
                options:
                  - proc.svg
                  - jak-dlouho.svg
                  - vzali-me.svg
                  - prisnejsi.svg
                  - vikend.svg
                  - navstevy.svg
                  - sam-ven.svg
                  - alkohol.svg
                  - mobil.svg
                  - wifi.svg
                  - kontrolovat.svg
                  - zamykat.svg
                  - soukromi.svg
                  - ss.svg
                  - kapesne.svg
                  - vyzdobit.svg
                  - pujcovani.svg
                  - vzhled.svg
                  - 18.svg
                  - nelibi.svg
                  - napsat.svg
                  - soud.png
                  - lecba.png
                  - nemocnice.png
                  - nesouhlas.png
              - editor_components:
                  - image
                buttons:
                  - bold
                  - italic
                  - link
                  - heading-two
                  - heading-three
                  - heading-four
                  - quote
                  - bulleted-list
                  - numbered-list
                label: Popis
                name: desc
                required: false
                widget: markdown
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Text
            name: body
            required: false
            widget: markdown
      - label: Čím se zabývá
        name: cim-se-zabyva
        file: content/kdo/cim-se-zabyva/index.markdown
        fields:
          - label: Titulek
            name: title
            widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Perex
            name: perex
            required: false
            widget: markdown
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Titulek - co může
            name: we-can-title
            required: false
            widget: markdown
          - label: Co může
            name: we-can
            required: false
            label_singular: položka
            widget: list
            fields:
              - label: Může
                name: text
                required: false
                widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Titulek - co nemůže
            name: we-cannot-title
            required: false
            widget: markdown
          - label: Co nemůže
            name: we-cannot
            required: false
            label_singular: položka
            widget: list
            fields:
              - label: Nemůže
                name: text
                required: false
                widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Text
            name: body
            required: false
            widget: markdown
        media_folder: ''
  - name: o ombudsmanovi
    label: Kdo je to ombudsman
    label_singular: kdo
    folder: content/kdo
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Perex
        name: perex
        required: false
        widget: markdown
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: pomoc
    label: Hledám pomoc
    label_singular: pomoc
    folder: content/pomoc
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Perex
        name: perex
        required: false
        widget: markdown
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: jsem
    label: Jsem v zařízení
    label_singular: zařízení
    folder: content/jsem
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - editor_components:
          - image
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Otázky
        name: questions
        required: false
        label_singular: otázka
        widget: list
        fields:
          - label: Otázka
            name: title
            widget: string
          - *ref_0
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Odpověď
            name: desc
            required: false
            widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: pripady
    label: Případy
    label_singular: oblast
    folder: content/pripady
    extension: md
    editor:
      preview: false
    fields:
      - label: Oblast
        name: title
        widget: string
      - label: Uložit jako draft
        name: draft
        required: false
        widget: boolean
      - label: Případy
        name: cases
        required: false
        label_singular: případ
        widget: list
        fields:
          - label: Situace
            name: title
            widget: string
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Perex
            name: perex
            required: false
            widget: markdown
          - editor_components:
              - image
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - quote
              - bulleted-list
              - numbered-list
            label: Text
            name: body
            required: false
            widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
