import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from '@tailwindcss/node';
import { Scanner } from '@tailwindcss/oxide';

const projectRoot = fileURLToPath(new URL('../', import.meta.url));
const inputPath = resolve(projectRoot, 'node_modules/@nuasite/cms/src/editor/styles.css');
const outputPath = resolve(projectRoot, 'src/styles/cms-editor.generated.css');
const sdkOutputPath = resolve(dirname(inputPath), 'styles.compiled.css');
const sdkEntryPath = resolve(dirname(inputPath), 'index.tsx');

/** Compile the SDK's explicit @source files, including project-patched controls. */
export async function compileCmsEditorStyles(): Promise<{ css: string; dependencies: string[] }> {
  const dependencies = new Set<string>([inputPath]);
  const input = (await readFile(inputPath, 'utf8')).replace('@import "tailwindcss";', '@import "tailwindcss" source(none);');
  const compiler = await compile(input, {
    base: dirname(inputPath),
    from: inputPath,
    onDependency: path => dependencies.add(path),
  });
  const scanner = new Scanner({ sources: compiler.sources });
  const css = '/* Generated by bun scripts/cms-editor-styles.ts from the installed patched CMS. */\n' + compiler.build(scanner.scan());
  for (const file of scanner.files) dependencies.add(file);
  if (!css.includes('.fixed {') || !css.includes('.flex {') || /@(?:source|theme|tailwind)\b/.test(css)) {
    throw new Error('Native CMS styles did not compile into usable Tailwind utilities.');
  }
  return { css, dependencies: [...dependencies] };
}

async function writeArtifact(css: string): Promise<void> {
  let previous = '';
  try { previous = await readFile(outputPath, 'utf8'); } catch { /* First generation. */ }
  if (previous === css) return;
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, css);
}

if (import.meta.main) {
  const { css } = await compileCmsEditorStyles();
  if (process.argv.includes('--check')) {
    if (await readFile(outputPath, 'utf8') !== css || await readFile(sdkOutputPath, 'utf8') !== css) throw new Error('CMS stylesheet is stale. Run bun scripts/cms-editor-styles.ts and refresh the SDK patch.');
    if (!(await readFile(sdkEntryPath, 'utf8')).includes("from './styles.compiled.css?inline'")) throw new Error('The CMS entry must import the compiled SDK stylesheet.');
    console.log('Verified compiled CMS shadow styles match patched editor controls.');
  } else {
    await writeArtifact(css);
    await writeFile(sdkOutputPath, css);
    console.log('Generated project and SDK compiled CMS styles; refresh the SDK patch before committing.');
  }
}
