name: deploy to production

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.105.0"
          extended: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install deps
        run: npm install

      - name: Build
        run: hugo

      - name: Compress build
        run: tar -zcf deti.tar.gz ./public

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./deti.tar.gz
          host: ${{ secrets.SSH_HOSTNAME }}
          remote: /home/ochrance/public_html
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unpack tar into place and link fileadmin
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ochrance/public_html
            mkdir deti-new
            tar -xf deti.tar.gz -C ./deti-new --strip-components=2
            mv deti deti-old
            mv deti-new deti
            rm -rf deti-old
